apiVersion : apps/v1
kind: Deployment
metadata:
  name: akannanspringbootapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: akannanspringbootapp
  template:
    metadata:
      labels:
        app: akannanspringbootapp
    spec:
      containers:
        - name: shri1082springbootapp 
          image: myacrrepo108.azurecr.io/akannanspringbootapp
          ports:
          - containerPort: 80
