apiVersion : apps/v1
kind: Deployment
metadata:
  name: shri1082springbootapp 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shri1082springbootapp
  template:
    metadata:
      labels:
        app: shri1082springbootapp 
    spec:
      containers:
        - name: shri1082springbootapp 
          image: myacrrepo108.azurecr.io/shri1082springbootapp
          ports:
          - containerPort: 80
